#!/usr/local/bin/bash

let many=10
let factor=10000

echo "Generating ${many} random input lists"

for (( much=1; much <= ${many}; much++ )); do
		most=`echo "${much}*${factor}" | bc`
		rm random.${most}.txt
		echo "#${most}"> random.${most}.txt
		for (( c=1; c <= ${most}; c++ )); do
			echo $RANDOM >> random.${most}.txt
		done    
done    
